import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import UploadFile from './components/uploadFile';



export default function Home() {
  return (
    <div className="ui container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="ui header">
        <h1 className="ui title">
          Welcome to<br/>
          <Link href="/list">Expense Reconciliation App</Link>
        </h1>

        <p className="ui header">
        Get started by uploading files{' '}
        <UploadFile/>
          <code className="ui code">Upload</code>
        </p>

        <div className="grid">
        <Link href="/list" >
          <div className="ui card">
            <div className="content">
            <h2>Reconcile Page &rarr;</h2>
              <p>Go through each transaction to do the splitting</p>
            </div>
          </div>
          </Link>

          <a href="https://nextjs.org/learn" className="ui card">
            <h2>Category Page &rarr;</h2>
            <p>Group transactions into set groups</p><br/><br/>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="ui card"
          >
            <h2>Dashboard Page &rarr;</h2>
            <p>Discover the past spent on different categories </p>
          </a>


        </div>
      </main>

      <footer className="ui footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Tom & Lu
        </a>
      </footer>
    </div>
  )
}
